var teams = {
  "ari": "Arizona Cardinals",
  "atl": "Atlanta Falcons",
  "bal": "Baltimore Ravens",
  "buf": "Buffalo Bills",
  "car": "Carolina Panthers",
  "chi": "Chicago Bears",
  "cin": "Cincinnati Bengals",
  "cle": "Cleveland Browns",
  "dal": "Dallas Cowboys",
  "den": "Denver Broncos",
  "det": "Detroit Lions",
  "gb": "Green Bay Packers",
  "hou": "Houston Texans",
  "ind": "Indianapolis Colts",
  "jax": "Jacksonville Jaguars",
  "kc": "Kansas City Chiefs",
  "lar": "Los Angeles Rams",
  "mia": "Miami Dolphins",
  "min": "Minnesota Vikings",
  "ne": "New England Patriots",
  "no": "New Orleans Saints",
  "nyg": "New York Giants",
  "nyj": "New York Jets",
  "oak": "Oakland Raiders",
  "phi": "Philadelphia Eagles",
  "pit": "Pittsburgh Steelers",
  "sd": "San Diego Chargers",
  "sea": "Seattle Seahawks",
  "sf": "San Francisco 49ers",
  "tb": "Tampa Bay Buccaneers",
  "ten": "Tennessee Titans",
  "was": "Washington Redskins",
  "bye": 'Bye'
}



export default {
  "ARI": [teams["ari"],teams["tb"],teams["buf"],teams["lar"],teams["sf"],teams["nyj"],teams["sea"],teams["car"],teams["bye"],teams["sf"],teams["min"],teams["atl"],teams["was"],teams["mia"],teams["no"],teams["sea"],teams["lar"]],
  "ATL": [teams["tb"],teams["oak"],teams["no"],teams["car"],teams["den"],teams["sea"],teams["sd"],teams["gb"],teams["tb"],teams["phi"],teams["bye"],teams["ari"],teams["kc"],teams["lar"],teams["sf"],teams["car"],teams["no"]],
  "BAL": [teams["buf"],teams["cle"],teams["jax"],teams["oak"],teams["was"],teams["nyg"],teams["nyj"],teams["bye"],teams["pit"],teams["cle"],teams["dal"],teams["cin"],teams["mia"],teams["ne"],teams["phi"],teams["pit"],teams["cin"]],
  "BUF": [teams["bal"],teams["nyj"],teams["ari"],teams["ne"],teams["lar"],teams["sf"],teams["mia"],teams["ne"],teams["sea"],teams["bye"],teams["cin"],teams["jax"],teams["oak"],teams["pit"],teams["cle"],teams["mia"],teams["nyj"]],
  "CAR": [teams["den"],,teams["sf"],teams["min"],teams["atl"],teams["tb"],teams["no"],teams["bye"],teams["ari"],teams["lar"],teams["kc"],teams["no"],teams["oak"],teams["sea"],teams["sd"],teams["was"],teams["atl"],teams["tb"]],
  "CHI": [teams["hou"],teams["phi"],teams["dal"],teams["det"],teams["ind"],teams["jax"],teams["gb"],teams["min"],teams["bye"],teams["tb"],teams["nyg"],teams["ten"],teams["sf"],teams["det"],teams["gb"],teams["was"],teams["min"]],
  "CIN": [teams["nyj"],teams["pit"],teams["den"],teams["mia"],teams["dal"],teams["ne"],teams["cle"],teams["was"],teams["bye"],teams["nyg"],teams["buf"],teams["bal"],teams["phi"],teams["cle"],teams["pit"],teams["hou"],teams["bal"]],
  "CLE": [teams["phi"],teams["bal"],teams["mia"],teams["was"],teams["ne"],teams["ten"],teams["cin"],teams["nyj"],teams["dal"],teams["bal"],teams["pit"],teams["nyg"],teams["bye"],teams["cin"],teams["buf"],teams["sd"],teams["pit"]],
  "DAL": [teams["nyg"],teams["was"],teams["chi"],teams["sf"],teams["cin"],teams["gb"],teams["bye"],teams["phi"],teams["cle"],teams["pit"],teams["bal"],teams["was"],teams["min"],teams["nyg"],teams["tb"],teams["det"],teams["phi"]],
  "DEN": [teams["car"],teams["ind"],teams["cin"],teams["tb"],teams["atl"],teams["sd"],teams["hou"],teams["sd"],teams["oak"],teams["no"],teams["bye"],teams["kc"],teams["jax"],teams["ten"],teams["ne"],teams["kc"],teams["oak"]],
  "DET": [teams["ind"],teams["ten"],teams["gb"],teams["chi"],teams["phi"],teams["lar"],teams["was"],teams["hou"],teams["min"],teams["bye"],teams["jax"],teams["min"],teams["no"],teams["chi"],teams["nyg"],teams["dal"],teams["gb"]],
  "GB": [teams["jax"],teams["min"],teams["det"],teams["bye"],teams["nyg"],teams["dal"],teams["chi"],teams["atl"],teams["ind"],teams["ten"],teams["was"],teams["phi"],teams["hou"],teams["sea"],teams["chi"],teams["min"],teams["det"]],
  "HOU": [teams["chi"],teams["kc"],teams["ne"],teams["ten"],teams["min"],teams["ind"],teams["den"],teams["det"],teams["bye"],teams["jax"],teams["oak"],teams["sd"],teams["gb"],teams["ind"],teams["jax"],teams["cin"],teams["ten"]],
  "IND": [teams["det"],teams["den"],teams["sd"],teams["jax"],teams["chi"],teams["hou"],teams["ten"],teams["kc"],teams["gb"],teams["bye"],teams["ten"],teams["pit"],teams["nyj"],teams["hou"],teams["min"],teams["oak"],teams["jax"]],
  "JAX": [teams["gb"],teams["sd"],teams["bal"],teams["ind"],teams["bye"],teams["chi"],teams["oak"],teams["ten"],teams["kc"],teams["hou"],teams["det"],teams["buf"],teams["den"],teams["min"],teams["hou"],teams["ten"],teams["ind"]],
  "KC": [teams["sd"],,teams["hou"],teams["nyj"],teams["pit"],teams["bye"],teams["oak"],teams["no"],teams["ind"],teams["jax"],teams["car"],teams["tb"],teams["den"],teams["atl"],teams["oak"],teams["ten"],teams["den"],teams["sd"]],
  "MIA": [teams["sea"],teams["ne"],teams["cle"],teams["cin"],teams["ten"],teams["pit"],teams["buf"],teams["bye"],teams["nyj"],teams["sd"],teams["lar"],teams["sf"],teams["bal"],teams["ari"],teams["nyj"],teams["buf"],teams["ne"]],
  "MIN": [teams["ten"],teams["gb"],teams["car"],teams["nyg"],teams["hou"],teams["bye"],teams["phi"],teams["chi"],teams["det"],teams["was"],teams["ari"],teams["det"],teams["dal"],teams["jax"],teams["ind"],teams["gb"],teams["chi"]],
  "NE": [teams["ari"],teams["mia"],,teams["hou"],teams["buf"],teams["cle"],teams["cin"],teams["pit"],teams["buf"],teams["bye"],teams["sea"],teams["sf"],teams["nyj"],teams["lar"],teams["bal"],teams["den"],teams["nyj"],teams["mia"]],
  "NO": [teams["oak"],,teams["nyg"],teams["atl"],teams["sd"],teams["bye"],teams["car"],teams["kc"],teams["sea"],teams["sf"],teams["den"],teams["car"],teams["lar"],teams["det"],teams["tb"],teams["ari"],teams["tb"],teams["atl"]],
  "NYG": [teams["dal"],teams["no"],teams["was"],teams["min"],teams["gb"],teams["bal"],teams["lar"],teams["bye"],teams["phi"],teams["cin"],teams["chi"],teams["cle"],teams["pit"],teams["dal"],teams["det"],teams["phi"],teams["was"]],
  "NYJ": [teams["cin"],teams["buf"],teams["kc"],teams["sea"],teams["pit"],teams["ari"],teams["bal"],teams["cle"],teams["mia"],teams["lar"],teams["bye"],teams["ne"],teams["ind"],teams["sf"],teams["mia"],teams["ne"],teams["buf"]],
  "OAK": [teams["no"],teams["atl"],teams["ten"],teams["bal"],teams["sd"],teams["kc"],teams["jax"],teams["tb"],teams["den"],teams["bye"],teams["hou"],teams["car"],teams["buf"],teams["kc"],teams["sd"],teams["ind"],teams["den"]],
  "PHI": [teams["cle"],teams["chi"],teams["pit"],teams["bye"],teams["det"],teams["was"],teams["min"],teams["dal"],teams["nyg"],teams["atl"],teams["sea"],teams["gb"],teams["cin"],teams["was"],teams["bal"],teams["nyg"],teams["dal"]],
  "PIT": [teams["was"],teams["cin"],teams["phi"],teams["kc"],teams["nyj"],teams["mia"],teams["ne"],teams["bye"],teams["bal"],teams["dal"],teams["cle"],teams["ind"],teams["nyg"],teams["buf"],teams["cin"],teams["bal"],teams["cle"]],
  "SD": [teams["kc"],teams["jax"],teams["ind"],teams["no"],teams["oak"],teams["den"],teams["atl"],teams["den"],teams["ten"],teams["mia"],teams["bye"],teams["hou"],teams["tb"],teams["car"],teams["oak"],teams["cle"],teams["kc"]],
  "SEA": [teams["mia"],teams["lar"],teams["sf"],teams["nyj"],teams["bye"],teams["atl"],teams["ari"],teams["no"],teams["buf"],teams["ne"],teams["phi"],teams["tb"],teams["car"],teams["gb"],teams["lar"],teams["ari"],teams["sf"]],
  "SF": [teams["lar"],teams["car"],teams["sea"],teams["dal"],teams["ari"],teams["buf"],teams["tb"],teams["bye"],teams["no"],teams["ari"],teams["ne"],teams["mia"],teams["chi"],teams["nyj"],teams["atl"],teams["lar"],teams["sea"]],
  "TB": [teams["hou"],teams["ari"],teams["lar"],teams["den"],teams["car"],teams["bye"],teams["sf"],teams["oak"],teams["atl"],teams["chi"],teams["kc"],teams["sea"],teams["sd"],teams["no"],teams["dal"],teams["no"],teams["car"]],
  "TEN": [teams["min"],teams["det"],teams["oak"],teams["hou"],teams["mia"],teams["cle"],teams["ind"],teams["jax"],teams["sd"],teams["gb"],teams["ind"],teams["chi"],teams["bye"],teams["den"],teams["kc"],teams["jax"],teams["hou"]],
  "WAS": [teams["pit"],teams["dal"],teams["nyg"],teams["cle"],teams["bal"],teams["phi"],teams["det"],teams["cin"],teams["bye"],teams["min"],teams["gb"],teams["dal"],teams["ari"],teams["phi"],teams["car"],teams["chi"],teams["nyg"]]
}
